<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_layar-settings',
		'title' => 'Layar Settings',
		'fields' => array (
			array (
				'key' => 'field_5324f07292efe',
				'label' => 'Layar Name',
				'name' => 'layar_name',
				'type' => 'text',
				'instructions' => 'The name of the layar as registered on the publishing site.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5324e928bf2fa',
				'label' => 'Hotspots',
				'name' => 'layar_hotspots',
				'type' => 'repeater',
				'instructions' => 'Register New Hotspots',
				'sub_fields' => array (
					array (
						'key' => 'field_5324e9b62b6cf',
						'label' => 'Reference Image',
						'name' => 'layar_reference_image',
						'type' => 'text',
						'instructions' => 'the name of the reference image on the layar.com publishing site under the pages section.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5324e9e82b6d0',
						'label' => 'Content Type',
						'name' => 'layar_content_type',
						'type' => 'select',
						'instructions' => 'The layar widget type.',
						'column_width' => '',
						'choices' => array (
							'text/html' => 'HTML',
							'video/mp4' => 'Video',
							'image/vnd.layar.generic' => 'Image',
							'model/vnd.layar.l3d' => '3D Model',
						),
						'default_value' => 'text/html',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_5324ea0e2b6d1',
						'label' => 'URL',
						'name' => 'layar_url',
						'type' => 'text',
						'instructions' => 'endpoint with the content you want to display on the layar.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5324ea372b6d2',
						'label' => 'Refresh Interval',
						'name' => 'layar_refresh_interval',
						'type' => 'number',
						'column_width' => '',
						'default_value' => 900,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_5324ea751bd69',
						'label' => 'Width',
						'name' => 'layar_width',
						'type' => 'number',
						'column_width' => '',
						'default_value' => 500,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_5324eab41bd6a',
						'label' => 'Height',
						'name' => 'layar_height',
						'type' => 'number',
						'column_width' => '',
						'default_value' => 300,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_5324eb951bd72',
						'label' => 'Size',
						'name' => 'layar_size',
						'type' => 'number',
						'column_width' => '',
						'default_value' => 1,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 0,
						'max' => '',
						'step' => '.0001',
					),
					array (
						'key' => 'field_5324ead11bd6c',
						'label' => 'Interactive',
						'name' => 'layar_interactive',
						'type' => 'true_false',
						'instructions' => 'The user can click on elements in this layar',
						'column_width' => '',
						'message' => '',
						'default_value' => 1,
					),
					array (
						'key' => 'field_5324eae71bd6d',
						'label' => 'Scrollable',
						'name' => 'layar_scrollable',
						'type' => 'true_false',
						'instructions' => 'the user can scroll the window in this layar',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_53c4867969a47',
						'label' => 'Rotate X',
						'name' => 'layar_rotate_x',
						'type' => 'true_false',
						'instructions' => 'rotate in the x direction',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_53c4872c69a48',
						'label' => 'Rotate Y',
						'name' => 'layar_rotate_y',
						'type' => 'true_false',
						'instructions' => 'rotate in the y direction',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_53c4874369a49',
						'label' => 'Rotate Z',
						'name' => 'layar_rotate_z',
						'type' => 'true_false',
						'instructions' => 'rotate in the z direction',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_53c48dbc8bce1',
						'label' => 'Rotate Relative',
						'name' => 'layar_rotate_rel',
						'type' => 'true_false',
						'instructions' => 'rotate relative to the user',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_53c4878469a4a',
						'label' => 'Rotate Angle',
						'name' => 'layar_rotate_angle',
						'type' => 'number',
						'column_width' => '',
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '-180',
						'max' => 180,
						'step' => '',
					),
					array (
						'key' => 'field_5324eb1e1bd6e',
						'label' => 'Translate X',
						'name' => 'layar_translate_x',
						'type' => 'number',
						'column_width' => '',
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '.001',
					),
					array (
						'key' => 'field_5324eb511bd6f',
						'label' => 'Translate Y',
						'name' => 'layar_translate_y',
						'type' => 'number',
						'column_width' => '',
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '.001',
					),
					array (
						'key' => 'field_5324eb5c1bd70',
						'label' => 'Translate Z',
						'name' => 'layar_translate_z',
						'type' => 'number',
						'column_width' => '',
						'default_value' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '.001',
					),
					array (
						'key' => 'field_5324eb6f1bd71',
						'label' => 'Scale',
						'name' => 'layar_scale',
						'type' => 'number',
						'column_width' => '',
						'default_value' => 1,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '.0001',
					),
					array (
						'key' => 'field_5324ebc543bb2',
						'label' => 'message',
						'name' => '',
						'type' => 'message',
						'column_width' => '',
						'message' => 'More translate options coming soon. Rotate, et all are on the way.',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Hotspot',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'layar',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nike-fa15-fields',
		'title' => 'Nike FA15 Fields',
		'fields' => array (
			array (
				'key' => 'field_545c4a913304e',
				'label' => 'Show App Menu',
				'name' => 'show_app_menu',
				'type' => 'select',
				'instructions' => 'Where to show the Nike.Net Apps on this page, if at all...',
				'choices' => array (
					'top' => 'At the Top',
					'bottom' => 'At the Bottom',
					'hidden' => 'Don\'t show it at all',
				),
				'default_value' => 'top',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_543f10025419c',
				'label' => 'Message pt 1',
				'name' => 'message_pt_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_543f100f5419d',
				'label' => 'Message pt 2',
				'name' => 'message_pt_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5441707f8a9d9',
				'label' => 'Message pt 3',
				'name' => 'message_pt_3',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_543f10285419e',
				'label' => 'Intro Mural Fields (get it??)',
				'name' => 'intro_mural_fields',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_543f103e5419f',
						'label' => 'Message pt 1',
						'name' => 'message_pt_1',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_543f1048541a1',
						'label' => 'Message pt 2',
						'name' => 'message_pt_2',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_543f1048541a0',
						'label' => 'Message pt 3',
						'name' => 'message_pt_3',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_54498f2fbf703',
				'label' => 'Background Image',
				'name' => 'background_image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_54498f40bf704',
				'label' => 'Quote Text',
				'name' => 'quote_text',
				'type' => 'textarea',
				'instructions' => 'Include quotation marks.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_54498f53bf705',
				'label' => 'Quote Source',
				'name' => 'quote_source',
				'type' => 'text',
				'instructions' => 'Do not include the dash before the source name.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54498f73bf706',
				'label' => 'Quote Text Color',
				'name' => 'quote_text_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a color for the text over the image.',
				'default_value' => '',
			),
			array (
				'key' => 'field_545981c55a490',
				'label' => 'Learn More Links',
				'name' => 'learn_more_links',
				'type' => 'repeater',
				'instructions' => 'Add one or more links to the footer.',
				'sub_fields' => array (
					array (
						'key' => 'field_545981da5a491',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'text',
						'instructions' => 'The URL to link to',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_545981e75a492',
						'label' => 'Label',
						'name' => 'label',
						'type' => 'text',
						'instructions' => 'The text to display for the link',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'nike_layar-content-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'nike-fa15-page.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_social-settings',
		'title' => 'Social Settings',
		'fields' => array (
			array (
				'key' => 'field_53335c3b93b76',
				'label' => 'Instagram CTA',
				'name' => 'mof_instagram_cta',
				'type' => 'textarea',
				'instructions' => 'The CTA that pops up when the instagram animation runs',
				'default_value' => 'Tag your instagrams #futuremural and they will show up here.',
				'placeholder' => '',
				'maxlength' => 140,
				'formatting' => 'br',
			),
			array (
				'key' => '',
				'label' => '',
				'name' => '',
				'type' => 'text',
				'default_value' => '',
				'formatting' => 'html',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_53336ed20f342',
				'label' => 'Looking for the Instagram hashtag?',
				'name' => '',
				'type' => 'message',
				'message' => 'Looking for the Instagram hashtag? It\'s in the Instagrate Pro Account. <a href="wp-admin/edit.php?post_type=instagrate_pro">Look here»</a>',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-center-panel.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
?>