<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_layar-settings',
		'title' => 'Layar Settings',
		'fields' => array (
			array (
				'key' => 'field_530aaa03dbe0f',
				'label' => 'Layar Setup',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_530aaab0f65be',
				'label' => 'Layar name',
				'name' => 'layar_name',
				'type' => 'text',
				'instructions' => 'the name of the layer registered on the Layar.com publishing site',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530aaae6f65bf',
				'label' => 'Reference Image',
				'name' => 'layar_reference_image',
				'type' => 'text',
				'instructions' => 'the name of the reference image on the layar.com publishing site under the pages section.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530aab1df65c0',
				'label' => 'Content Type',
				'name' => 'layar_content_type',
				'type' => 'select',
				'choices' => array (
					'text/html' => 'HTML',
					'video/mp4' => 'Video',
					'image/vnd.layar.generic' => 'Image',
				),
				'default_value' => 'text/html',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_530aaba6f65c1',
				'label' => 'URL',
				'name' => 'layar_url',
				'type' => 'text',
				'instructions' => 'endpoint with the content you want to display on the layar.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530aade31f34a',
				'label' => 'Refresh Interval',
				'name' => 'layar_refresh_interval',
				'type' => 'number',
				'default_value' => 900,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_530aaa2258027',
				'label' => 'Viewport & Size',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_530aabdd2e081',
				'label' => 'Width',
				'name' => 'layar_width',
				'type' => 'number',
				'default_value' => 579,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_530aac092e082',
				'label' => 'Height',
				'name' => 'layar_height',
				'type' => 'number',
				'default_value' => 300,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_530aac443362d',
				'label' => 'Interactive',
				'name' => 'layar_interactive',
				'type' => 'true_false',
				'instructions' => 'The user interact with the content in the layar.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_530aac703362e',
				'label' => 'Scrollable',
				'name' => 'layar_scrollable',
				'type' => 'true_false',
				'instructions' => 'The layar content is scrollable.',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_530aad63009d1',
				'label' => 'Size',
				'name' => 'layar_size',
				'type' => 'number',
				'default_value' => 1,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_530aaa6a58028',
				'label' => 'Transform',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_530aacee009cd',
				'label' => 'Translate X',
				'name' => 'layar_translate_x',
				'type' => 'number',
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_530aad0f009ce',
				'label' => 'Translate Y',
				'name' => 'layar_translate_y',
				'type' => 'number',
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_530aad24009cf',
				'label' => 'Translate Z',
				'name' => 'layar_translate_z',
				'type' => 'number',
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_530aad30009d0',
				'label' => 'Scale',
				'name' => 'layar_scale',
				'type' => 'number',
				'default_value' => 1,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_530aad9b009d2',
				'label' => 'message',
				'name' => '',
				'type' => 'message',
				'message' => 'More translate options coming soon. Rotate, et all are on the way.',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'layar',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'discussion',
				2 => 'comments',
			),
		),
		'menu_order' => 0,
	));
}
?>